version: "3.7"
services:
        mongodb:
                image: mongo
                container_name: 'mongobd'
                restart: always
                environment:
                        - MONGO_INITDB_DATABASE=orders
                        - MONGO_INITDB_ROOT_USERNAME=root
                        - MONGO_INITDB_ROOT_PASSWORD=root
                volumes:
                        - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
                ports:
                        - '27017-27019:27017-27019'
